import {
  Building2,
  FileText,
  Files,
  Package,
  Radio,
  Cable,
  PhoneCall,
} from "lucide-react";
import {
  clientsApi,
  legalDocumentsApi,
  masterDocumentsApi,
  productsApi,
  channelsApi,
  clientProductChannelsApi,
  callingConfigsApi,
} from "../api/clientPlatform";
import { ROUTES } from "../lib/constants";

const timestampColumns = [
  { key: "created_at", label: "Created", type: "date" },
  { key: "updated_at", label: "Updated", type: "date" },
];

const jsonStringify = (value) => {
  if (value === null || value === undefined) return "";
  if (typeof value === "string") return value;
  try {
    return JSON.stringify(value, null, 2);
  } catch {
    return String(value);
  }
};

export const clientResources = {
  clients: {
    key: "clients",
    path: ROUTES.client.clients,
    title: "Clients",
    singular: "Client",
    description: "Organizations onboarded and configured on the platform.",
    icon: Building2,
    api: clientsApi,
    idKey: "client_id",
    idLabel: "Client ID",
    hasList: true,
    useMultipart: true,
    fields: [
      {
        name: "name",
        label: "Display name",
        type: "text",
        required: true,
        minLength: 2,
        maxLength: 100,
        placeholder: "Acme Corp",
      },
      {
        name: "legal_name",
        label: "Legal name",
        type: "text",
        required: true,
        minLength: 2,
        maxLength: 200,
        placeholder: "Acme Corporation Pvt. Ltd.",
      },
      {
        name: "logo",
        label: "Logo URL",
        type: "url",
        maxLength: 500,
        placeholder: "https://…",
      },
      {
        name: "primary_contact",
        label: "Primary contact",
        type: "text",
        validate: "personName",
        maxLength: 100,
        placeholder: "Jane Doe",
        getValue: (r) => r?.client_contacts?.primary_contact,
      },
      {
        name: "email",
        label: "Contact email",
        type: "email",
        required: true,
        maxLength: 254,
        placeholder: "contact@acme.com",
        getValue: (r) => r?.client_contacts?.email,
      },
      {
        name: "phone",
        label: "Contact phone",
        type: "phone",
        required: true,
        minLength: 10,
        maxLength: 10,
        placeholder: "9876543210",
        getValue: (r) => r?.client_contacts?.phone,
      },
      {
        name: "host",
        label: "Server host",
        type: "text",
        validate: "host",
        maxLength: 253,
        placeholder: "mail.acme.com",
        getValue: (r) => r?.server_details?.host,
      },
      {
        name: "port",
        label: "Server port",
        type: "number",
        integer: true,
        min: 1,
        max: 65535,
        placeholder: "443",
        getValue: (r) => r?.server_details?.port,
      },
      {
        name: "environment",
        label: "Environment",
        type: "text",
        validate: "slug",
        maxLength: 50,
        placeholder: "production",
        getValue: (r) => r?.server_details?.environment,
      },
    ],
    columns: [
      { key: "client_id", label: "ID" },
      { key: "name", label: "Name" },
      { key: "legal_name", label: "Legal name" },
      { key: "status", label: "Status", type: "boolean" },
    ],
  },

  legalDocuments: {
    key: "legalDocuments",
    path: ROUTES.client.legalDocuments,
    title: "Legal Documents",
    singular: "Legal Document",
    createAction: "Upload",
    createModalTitle: "Upload document",
    createModalDescription: "Select the document type and choose a file to upload.",
    createSubmitLabel: "Upload",
    createSuccessMessage: "Document uploaded.",
    description: "Client-specific legal documents uploaded against master document types.",
    icon: FileText,
    api: legalDocumentsApi,
    idKey: "id",
    idLabel: "Document ID",
    hasList: true,
    useMultipart: true,
    filterByClient: true,
    fields: [
      {
        name: "client_id",
        label: "Client ID",
        type: "number",
        required: true,
        clientDefault: true,
        createOnly: true,
        hidden: true,
      },
      {
        name: "master_id",
        label: "Document type",
        type: "masterDocument",
        required: true,
        createOnly: true,
        help: "Required documents must be uploaded. Optional documents can be added when available.",
      },
      {
        name: "document",
        label: "Document file",
        type: "file",
        required: true,
        help: "PDF or image file to upload.",
      },
      {
        name: "is_verified",
        label: "Verified",
        type: "boolean",
        editOnly: true,
        booleanLabels: { true: "Verified", false: "Not verified" },
        getValue: (r) => r?.is_verified,
      },
    ],
    columns: [
      { key: "id", label: "ID" },
      {
        key: "master_id",
        label: "Master doc",
        accessor: (r) =>
          r.master_document?.document_name
            ? `${r.master_document.document_name} (#${r.master_id})`
            : r.master_id,
      },
      { key: "original_filename", label: "Filename" },
      { key: "document_url", label: "Document", type: "link" },
      { key: "is_verified", label: "Verified", type: "boolean" },
      ...timestampColumns,
    ],
  },

  masterDocuments: {
    key: "masterDocuments",
    path: ROUTES.client.masterDocuments,
    title: "Master Documents",
    singular: "Master Document",
    description: "Document types that clients must upload as legal documents.",
    icon: Files,
    api: masterDocumentsApi,
    idKey: "id",
    idLabel: "Document ID",
    hasList: true,
    useFormUrlEncoded: true,
    fields: [
      {
        name: "document_name",
        label: "Document name",
        type: "text",
        required: true,
        placeholder: "GST Certificate",
      },
      {
        name: "mandatory",
        label: "Mandatory",
        type: "boolean",
        required: true,
        defaultValue: true,
        booleanLabels: { true: "Mandatory", false: "Optional" },
      },
    ],
    columns: [
      { key: "id", label: "ID" },
      { key: "document_name", label: "Name" },
      { key: "mandatory", label: "Mandatory", type: "boolean" },
    ],
  },

  masterProducts: {
    key: "masterProducts",
    path: ROUTES.client.products,
    title: "Master Products",
    singular: "Product",
    description: "Products offered across the platform.",
    icon: Package,
    api: productsApi,
    idKey: "id",
    idLabel: "Product ID",
    hasList: true,
    useFormUrlEncoded: true,
    fields: [
      {
        name: "name",
        label: "Product name",
        type: "text",
        required: true,
        placeholder: "Loan Recovery",
      },
    ],
    columns: [
      { key: "id", label: "ID" },
      { key: "name", label: "Name" },
      ...timestampColumns,
    ],
  },

  masterChannels: {
    key: "masterChannels",
    path: ROUTES.client.channels,
    title: "Master Channels",
    singular: "Channel",
    description: "Communication channels such as voice, SMS, or WhatsApp.",
    icon: Radio,
    api: channelsApi,
    idKey: "id",
    idLabel: "Channel ID",
    hasList: true,
    useFormUrlEncoded: true,
    fields: [
      {
        name: "type",
        label: "Channel type",
        type: "text",
        required: true,
        placeholder: "voice, sms, whatsapp",
      },
    ],
    columns: [
      { key: "id", label: "ID" },
      { key: "type", label: "Type" },
      ...timestampColumns,
    ],
  },

  productChannels: {
    key: "productChannels",
    path: ROUTES.client.productChannels,
    title: "Product Channels",
    singular: "Product Channel",
    description: "Maps a client to a product and channel combination.",
    icon: Cable,
    api: clientProductChannelsApi,
    idKey: "id",
    idLabel: "Mapping ID",
    hasList: true,
    useFormUrlEncoded: true,
    filterByClient: true,
    fields: [
      {
        name: "client_id",
        label: "Client ID",
        type: "number",
        required: true,
        clientDefault: true,
        createOnly: true,
        hidden: true,
      },
      {
        name: "product_id",
        label: "Product",
        type: "product",
        required: true,
        createOnly: true,
      },
      {
        name: "channel_id",
        label: "Channel",
        type: "channel",
        required: true,
        createOnly: true,
      },
      {
        name: "storage_url",
        label: "Storage URL",
        type: "text",
        placeholder: "https://…",
      },
      {
        name: "api_enabled",
        label: "API enabled",
        type: "boolean",
        required: true,
        defaultValue: true,
        booleanLabels: { true: "Enabled", false: "Disabled" },
      },
    ],
    columns: [
      { key: "id", label: "ID" },
      { key: "client_id", label: "Client" },
      {
        key: "product",
        label: "Product",
        accessor: (r) =>
          r.product?.name ? `${r.product.name} (#${r.product_id})` : r.product_id,
      },
      {
        key: "channel",
        label: "Channel",
        accessor: (r) =>
          r.channel?.type ? `${r.channel.type} (#${r.channel_id})` : r.channel_id,
      },
      { key: "storage_url", label: "Storage URL" },
      { key: "api_enabled", label: "API", type: "boolean" },
      ...timestampColumns,
    ],
  },

  callingConfig: {
    key: "callingConfig",
    path: ROUTES.client.callingConfig,
    title: "Calling Config",
    singular: "Calling Config",
    description: "Calling behaviour settings for a client product channel.",
    icon: PhoneCall,
    api: callingConfigsApi,
    idKey: "id",
    idLabel: "Config ID",
    hasList: true,
    useFormUrlEncoded: true,
    filterByClient: true,
    filterClientId: (record) => record.client_product_channel?.client_id,
    modalSize: "3xl",
    formColumns: 3,
    fields: [
      {
        name: "client_product_channel_id",
        label: "Product channel",
        type: "clientProductChannel",
        required: true,
        createOnly: true,
        colSpan: "full",
      },
      {
        name: "lines_config",
        label: "Lines config (JSON)",
        type: "textarea",
        required: true,
        colSpan: 2,
        rows: 5,
        placeholder: '{"max_simultaneous_calls": 5}',
        help: "JSON string for lines configuration.",
        getValue: (r) => jsonStringify(r?.lines_config),
      },
      {
        name: "allowed_timeline",
        label: "Allowed timeline (JSON)",
        type: "textarea",
        required: true,
        colSpan: 1,
        rows: 5,
        placeholder: '{"start_time": "09:00", "end_time": "18:00"}',
        help: "Permitted calling window.",
        getValue: (r) => jsonStringify(r?.allowed_timeline),
      },
      {
        name: "language",
        label: "Language",
        type: "language",
        required: true,
      },
      {
        name: "min_retries",
        label: "Min retries",
        type: "number",
        placeholder: "3",
      },
      {
        name: "llm_id",
        label: "LLM model",
        type: "llmModel",
        createOnly: true,
      },
      {
        name: "stt_id",
        label: "STT model",
        type: "sttModel",
        createOnly: true,
      },
      {
        name: "tts_id",
        label: "TTS model",
        type: "ttsModel",
        createOnly: true,
      },
      {
        name: "is_multilingual_switching_enabled",
        label: "Multilingual switching",
        type: "boolean",
        defaultValue: false,
        booleanLabels: { true: "Enabled", false: "Disabled" },
      },
      {
        name: "is_tts_enabled",
        label: "TTS enabled",
        type: "boolean",
        defaultValue: false,
        booleanLabels: { true: "Yes", false: "No" },
      },
      {
        name: "is_audio_enabled",
        label: "Audio enabled",
        type: "boolean",
        defaultValue: false,
        booleanLabels: { true: "Yes", false: "No" },
      },
    ],
    columns: [
      { key: "id", label: "ID" },
      { key: "client_product_channel_id", label: "Product channel" },
      { key: "language", label: "Language" },
      { key: "min_retries", label: "Retries" },
      { key: "is_tts_enabled", label: "TTS", type: "boolean" },
      { key: "is_audio_enabled", label: "Audio", type: "boolean" },
      ...timestampColumns,
    ],
  },
};

export const clientResourceList = Object.values(clientResources);
